// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gibbsC
NumericMatrix gibbsC(double mu_x, double mu_y, double sig_x, double sig_y, double rho, double init_x, double init_y, int N);
RcppExport SEXP _StatComp22062_gibbsC(SEXP mu_xSEXP, SEXP mu_ySEXP, SEXP sig_xSEXP, SEXP sig_ySEXP, SEXP rhoSEXP, SEXP init_xSEXP, SEXP init_ySEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mu_x(mu_xSEXP);
    Rcpp::traits::input_parameter< double >::type mu_y(mu_ySEXP);
    Rcpp::traits::input_parameter< double >::type sig_x(sig_xSEXP);
    Rcpp::traits::input_parameter< double >::type sig_y(sig_ySEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type init_x(init_xSEXP);
    Rcpp::traits::input_parameter< double >::type init_y(init_ySEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbsC(mu_x, mu_y, sig_x, sig_y, rho, init_x, init_y, N));
    return rcpp_result_gen;
END_RCPP
}
// matmultC
NumericMatrix matmultC(NumericMatrix matA, NumericMatrix matB);
RcppExport SEXP _StatComp22062_matmultC(SEXP matASEXP, SEXP matBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type matA(matASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type matB(matBSEXP);
    rcpp_result_gen = Rcpp::wrap(matmultC(matA, matB));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StatComp22062_gibbsC", (DL_FUNC) &_StatComp22062_gibbsC, 8},
    {"_StatComp22062_matmultC", (DL_FUNC) &_StatComp22062_matmultC, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_StatComp22062(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
