# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbsC <- function(mu_x, mu_y, sig_x, sig_y, rho, init_x, init_y, N) {
    .Call('_StatComp22062_gibbsC', PACKAGE = 'StatComp22062', mu_x, mu_y, sig_x, sig_y, rho, init_x, init_y, N)
}

#' @title matrix multiplication
#' @description Compute the result of matrix multiplication in cpp
#' @param matA a matrix
#' @param matB another matrix with which matA can do a matrix multiplication
#' @return The result C of C=AB
#' @examples
#' \dontrun{
#' mat1 = matrix(rnorm(15),nrow = 3,ncol = 5)
#' mat2 = matrix(rnorm(30),nrow = 5,ncol = 6)
#' c = matmultC(mat1,mat2)
#' print(c)
#' }
#' @export
#' @useDynLib StatComp22062
matmultC <- function(matA, matB) {
    .Call('_StatComp22062_matmultC', PACKAGE = 'StatComp22062', matA, matB)
}

